/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface Poe1AscendancyTree {
        /**
          * The urlTree
         */
        "urlTree": string;
    }
    interface Poe1Tree {
        /**
          * The urlTree
         */
        "urlTree": string;
    }
}
declare global {
    interface HTMLPoe1AscendancyTreeElement extends Components.Poe1AscendancyTree, HTMLStencilElement {
    }
    var HTMLPoe1AscendancyTreeElement: {
        prototype: HTMLPoe1AscendancyTreeElement;
        new (): HTMLPoe1AscendancyTreeElement;
    };
    interface HTMLPoe1TreeElement extends Components.Poe1Tree, HTMLStencilElement {
    }
    var HTMLPoe1TreeElement: {
        prototype: HTMLPoe1TreeElement;
        new (): HTMLPoe1TreeElement;
    };
    interface HTMLElementTagNameMap {
        "poe1-ascendancy-tree": HTMLPoe1AscendancyTreeElement;
        "poe1-tree": HTMLPoe1TreeElement;
    }
}
declare namespace LocalJSX {
    interface Poe1AscendancyTree {
        /**
          * The urlTree
         */
        "urlTree"?: string;
    }
    interface Poe1Tree {
        /**
          * The urlTree
         */
        "urlTree"?: string;
    }
    interface IntrinsicElements {
        "poe1-ascendancy-tree": Poe1AscendancyTree;
        "poe1-tree": Poe1Tree;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "poe1-ascendancy-tree": LocalJSX.Poe1AscendancyTree & JSXBase.HTMLAttributes<HTMLPoe1AscendancyTreeElement>;
            "poe1-tree": LocalJSX.Poe1Tree & JSXBase.HTMLAttributes<HTMLPoe1TreeElement>;
        }
    }
}
